# see http://about.travis-ci.org/docs/user/languages/php/ for more hints

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

# TODO https://docs.travis-ci.com/user/database-setup/#MariaDB
services:
  - mysql

before_script:
  - sh -c "mysql -e 'CREATE DATABASE IF NOT EXISTS `phoenix`;'"
  - sh -c "mysql -e 'CREATE USER phoenix@localhost IDENTIFIED BY 'Password1';'"
  - sh -c "mysql -e 'GRANT ALL PRIVILEGES ON *.* TO phoenix@localhost;'"
  - sh -c "mysql -e 'FLUSH PRIVILEGES;'"
  - git clone https://github.com/eustasy/normal-checks.git

script:
  - ./normal-checks/php.sh
  - php normal-checks/json.php
  - php normal-checks/xml.php
  - php _functions/phoenix/test.tracker.clean.php

notifications:
  email:
    recipients:
      - lewisgoddard@eustasy.org
    on_success: change
    on_failure: always
